services:
  backend:
    build:
      context: ./todo-api
    ports:
      - 8000:8000
    volumes:
      - ./todo-api:/app
    environment:
      - API_PORT=some value here
      - MONGO_URL=some value here
      - JWT_ACCESS_TOKEN_SECRET=some value here
      - JWT_ACCESS_TOKEN_EXPIRES_IN=some value here
      - JWT_REFRESH_TOKEN_SECRET=some value here
      - JWT_REFRESH_TOKEN_EXPIRES_IN=some value here
    networks:
      - mynetwork

  frontend:
    build:
      context: ./front
    ports:
      - 3000:80
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
